<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" href="public/css/style.css">
</head>

<body>
    <div class="container">
        <h1>Inicia sesión</h1>
        <form action="index.php?c=usuarios" method="post">
            <input type="text" name="nombre_usuario" placeholder="Nombre de usuario" required>
            <input type="password" name="contrasena" placeholder="Contraseña" required>
            <input type="submit" value="Iniciar sesión">
        </form>

        <div style="text-align: center; margin-top: 20px;">
            <a href="index.php?c=usuarios&register=1">¿No tienes cuenta? Regístrate</a>
        </div>
    </div>
</body>

</html>